name: Script
main: com.mengcraft.script.ScriptBootstrap
version: ${project.version}
author: caoli5288
website: http://github.com/caoli5288/script/
softdepend:
- 'PlaceholderAPI'

commands:
  script:
    description: JavaScript plugin loader. http://github.com/caoli5288/script/